import '@/styles/globals.css';
import type { Metadata } from 'next';

// 導入Context Provider
import { AuthProvider } from '@/hooks/use-Auth';
// 導入 context soket
import { SocketProvider } from '@/hooks/use-Socket';

import Navbar from '../components/layout/Navbar';
import Footer from '../components/layout/Footer';
import { useContext } from 'react';

export const metadata: Metadata = {
  title: '旅行背包',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <SocketProvider>
            <Navbar />
            {children}
            <Footer />
          </SocketProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
