import '@/styles/globals.css';
import type { Metadata } from 'next';
import 'slick-carousel/slick/slick.css';
import 'slick-carousel/slick/slick-theme.css';

// 導入Context Provider
import { AuthProvider } from '@/hooks/use-Auth';
// 導入 context soket
import { SocketProvider } from '@/hooks/use-Socket';

// m3 收藏
import { FavoriteAccommodationProvider } from '../contexts/FavoriteAccommodationContext';

import Navbar from '../components/layout/Navbar';
import Footer from '../components/layout/Footer';

import { Noto_Sans_TC, Roboto } from 'next/font/google';
import ToastProvider from '../components/ui/ToastProvider';

// 1. 定義 Roboto 字型 (處理英文字和數字)
const roboto = Roboto({
  weight: ['400', '500', '700'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-roboto', // 定義 CSS 變數
});

// 2. 定義 Noto Sans TC 字型 (處理繁體中文字)
const noto_sans_tc = Noto_Sans_TC({
  weight: ['400', '500', '700'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-noto-sans-tc', // 定義 CSS 變數
});

export const metadata: Metadata = {
  title: '旅行背包',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${roboto.variable} ${noto_sans_tc.variable} font-sans`}
    >
      <body>
        <AuthProvider>
          <SocketProvider>
            <FavoriteAccommodationProvider>
              <ToastProvider>
                <Navbar />
                {children}
                <Footer />
              </ToastProvider>
            </FavoriteAccommodationProvider>
          </SocketProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
